# Generated by Django 5.1.2 on 2024-10-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_reply_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
